spring:
  datasource:
    url: jdbc:sqlserver://devtcc.database.windows.net:1433;database=devtcc;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: devtcc
    password: Tcc2024*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8081